# Generated by Django 3.0.5 on 2020-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='Datelogged',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='Important',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='Targetdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='Urgent',
            field=models.BooleanField(null=True),
        ),
    ]
